using Beats.Production.Contracts;
using Beats.Production.Contracts.Events;
using Beats.Production.Contracts.Events.Payloads;
using Beats.Production.Flows;
using Beats.Production.Contracts.Media;
using Beats.Production.Contracts.Productions;
using Beats.Production.Contracts.Storyboarding;
using Beats.Production.Middleware.Ai;
using Beats.Production.Middleware.Artifacts;
using Beats.Production.Middleware.Eventing;
using Beats.Production.Middleware.Persistence;
using Beats.Production.Middleware.Specifications;
using MassTransit;
using Microsoft.Extensions.Options;

namespace Beats.Agents.Illustrator;

public sealed class StoryCreatedConsumer(
    IArtifactStore artifactStore,
    IEventPublisher eventPublisher,
    IImageGenerationClient imageGenerationClient,
    IOptions<ComfyUiOptions> comfyUiOptions,
    IProductionFlow productionFlow,
    IProductionRepository productionRepository,
    IProductionSpecValidator productionSpecValidator,
    ILogger<StoryCreatedConsumer> logger) : IConsumer<EventEnvelope<CommonPayload>>
{
    private readonly ComfyUiOptions _comfyUiOptions = comfyUiOptions.Value;

    public async Task Consume(ConsumeContext<EventEnvelope<CommonPayload>> context)
    {
        var incoming = context.Message;

        if (!productionFlow.IsSubscribedTo(AgentRoles.Illustrator, incoming.EventType))
        {
            return;
        }

        var specValidation = await productionSpecValidator.ValidateAsync(
            incoming,
            AgentRoles.Illustrator,
            context.CancellationToken);
        EnsureValidSpec(specValidation);

        var startedAt = DateTimeOffset.UtcNow;
        var storyArtifact = GetRequiredArtifact(incoming, "storyUri");
        var sceneBreakdownArtifact = GetRequiredArtifact(incoming, "sceneBreakdownUri", "scenesUri");

        logger.LogInformation(
            "{AgentRole} consumed {EventType}. ProductionId={ProductionId}, Scenes={ScenesArtifact}",
            AgentRoles.Illustrator,
            incoming.EventType,
            incoming.ProductionId,
            sceneBreakdownArtifact.Uri);

        await Task.Delay(TimeSpan.FromSeconds(2), context.CancellationToken);

        var sceneBreakdown = await ArtifactJson.ReadAsync<SceneBreakdownDocument>(
            artifactStore,
            sceneBreakdownArtifact.Uri,
            context.CancellationToken);

        var scenes = sceneBreakdown.Scenes
            .OrderBy(scene => scene.Order)
            .Take(Math.Clamp(_comfyUiOptions.MaxScenes, 1, 12))
            .ToArray();
        var style = string.IsNullOrWhiteSpace(sceneBreakdown.Style)
            ? incoming.Payload.Attributes.GetValueOrDefault("style") ?? "watercolor storybook"
            : sceneBreakdown.Style;
        var imageArtifacts = new List<SceneArtifact>();
        var manifestItems = new List<object>();

        logger.LogInformation(
            "{AgentRole} extracted {SceneCount} scene(s). ProductionId={ProductionId}",
            AgentRoles.Illustrator,
            scenes.Length,
            incoming.ProductionId);

        foreach (var scene in scenes)
        {
            logger.LogInformation(
                "{AgentRole} generating image for {SceneId}. ProductionId={ProductionId}",
                AgentRoles.Illustrator,
                scene.SceneId,
                incoming.ProductionId);

            var image = await imageGenerationClient.GenerateAsync(
                new ImageGenerationRequest(
                    BuildImagePrompt(scene, style),
                    NegativePrompt: "text, watermark, logo, signature, blurry, low quality, extra fingers, deformed hands, distorted face",
                    FileNamePrefix: $"beats-{incoming.ProductionId:N}-{scene.SceneId}"),
                context.CancellationToken);

            await using var imageStream = new MemoryStream(image.Content);
            var imageUri = await artifactStore.SaveAsync(
                imageStream,
                $"productions/{incoming.ProductionId}/02-illustrator/{scene.SceneId}.png",
                image.MediaType,
                context.CancellationToken);

            var imageArtifact = new ArtifactReference(
                imageUri,
                image.MediaType,
                $"{scene.Title}. Generated by Illustrator with ComfyUI FLUX quantized. PromptId={image.PromptId}.");

            imageArtifacts.Add(new SceneArtifact(scene.SceneId, imageArtifact, scene.Order));

            await productionRepository.RecordArtifactAsync(
                incoming.ProductionId,
                AgentRoles.Illustrator,
                imageArtifact,
                context.CancellationToken);

            manifestItems.Add(new
            {
                scene.SceneId,
                scene.Order,
                scene.Title,
                ArtifactUri = imageUri,
                image.MediaType,
                image.FileName,
                image.PromptId,
                image.TotalDuration
            });
        }

        var manifest = new
        {
            ProductionId = incoming.ProductionId,
            SourceStoryUri = storyArtifact.Uri,
            SourceSceneBreakdownUri = sceneBreakdownArtifact.Uri,
            ComfyUiModel = _comfyUiOptions.Model,
            Style = style,
            Images = manifestItems
        };

        var manifestUri = await ArtifactJson.SaveAsync(
            artifactStore,
            manifest,
            $"productions/{incoming.ProductionId}/02-illustrator/image-manifest.json",
            context.CancellationToken);

        var manifestArtifact = new ArtifactReference(
            manifestUri,
            "application/json",
            "Image manifest describing scene images generated by the illustrator agent.");

        await productionRepository.RecordArtifactAsync(
            incoming.ProductionId,
            AgentRoles.Illustrator,
            manifestArtifact,
            context.CancellationToken);

        var publication = productionFlow.GetRequiredPublication<CommonPayload>(
            AgentRoles.Illustrator,
            incoming.EventType);

        var outputArtifacts = imageArtifacts
            .OrderBy(image => image.Order)
            .Select(image => image.Artifact)
            .Append(manifestArtifact)
            .ToArray();

        var payload = CommonPayload.Create(
            publication.EventType,
            AgentRoles.Illustrator,
            attributes: new Dictionary<string, string>(incoming.Payload.Attributes)
            {
                ["manifestUri"] = manifestArtifact.Uri,
                ["imageManifestUri"] = manifestArtifact.Uri,
                ["imageCount"] = imageArtifacts.Count.ToString()
            },
            artifacts: outputArtifacts,
            data: new Dictionary<string, object?>
            {
                ["comfyUiModel"] = _comfyUiOptions.Model,
                ["maxScenes"] = _comfyUiOptions.MaxScenes
            });

        var outgoing = EventEnvelope<CommonPayload>.Create(
            publication.EventType,
            incoming.ProductionId,
            AgentRoles.Illustrator,
            payload,
            incoming.CorrelationId,
            incoming.EventId);

        await productionRepository.RecordAgentRunAsync(
            new AgentRunRecord(
                Guid.NewGuid(),
                incoming.ProductionId,
                AgentRoles.Illustrator,
                incoming.EventId,
                outgoing.EventId,
                storyArtifact.Uri,
                manifestArtifact.Uri,
                "Completed",
                startedAt,
                DateTimeOffset.UtcNow,
                $"Generated {imageArtifacts.Count} scene image artifact(s) with ComfyUI FLUX quantized."),
            context.CancellationToken);

        await productionRepository.RecordEventAsync(outgoing, context.CancellationToken);
        await productionRepository.UpdateProductionStatusAsync(
            incoming.ProductionId,
            ProductionStatus.ImagesCreated.ToString(),
            context.CancellationToken);

        await eventPublisher.PublishAsync(outgoing, context.CancellationToken);
    }

    private static ArtifactReference GetRequiredArtifact(
        EventEnvelope<CommonPayload> incoming,
        params string[] outputKeys)
    {
        foreach (var outputKey in outputKeys)
        {
            if (incoming.Payload.Attributes.TryGetValue(outputKey, out var uri) &&
                !string.IsNullOrWhiteSpace(uri))
            {
                return incoming.Payload.Artifacts.FirstOrDefault(artifact => artifact.Uri == uri) ??
                    new ArtifactReference(uri, "application/octet-stream");
            }
        }

        return incoming.Payload.Artifacts.First();
    }

    private static string BuildImagePrompt(SceneBreakdownItem scene, string style)
    {
        return $"""
            Create one finished illustration for a story video scene.
            Visual style: {style}, Taiwanese picture-book sensibility, coherent character design, warm cinematic lighting, gentle watercolor texture, clean composition, no visible text.
            Scene id: {scene.SceneId}
            Scene title: {scene.Title}
            Visual description: {scene.VisualDescription}
            Character action: {scene.CharacterAction}
            Mood and color: {scene.MoodAndColor}
            Illustrator direction: {scene.IllustratorPrompt}
            Requirements: single frame, emotionally clear, consistent style across scenes, suitable as a key visual for animation.
            """;
    }

    private static void EnsureValidSpec(ProductionSpecValidationResult validation)
    {
        if (!validation.IsValid)
        {
            throw new InvalidOperationException(
                $"Production spec preflight failed for {validation.Stage.AgentRole}: {string.Join("; ", validation.Errors)}");
        }
    }
}
