using Beats.Production.Contracts;
using Beats.Production.Contracts.Events;
using Beats.Production.Contracts.Events.Payloads;
using Beats.Production.Flows;
using Beats.Production.Contracts.Media;
using Beats.Production.Contracts.Productions;
using Beats.Production.Middleware.Artifacts;
using Beats.Production.Middleware.Eventing;
using Beats.Production.Middleware.Persistence;
using Beats.Production.Middleware.Specifications;
using MassTransit;

namespace Beats.Agents.Reviewer;

public sealed class FinalVideoCreatedConsumer(
    IArtifactStore artifactStore,
    IEventPublisher eventPublisher,
    IProductionFlow productionFlow,
    IProductionRepository productionRepository,
    IProductionSpecValidator productionSpecValidator,
    ILogger<FinalVideoCreatedConsumer> logger) : IConsumer<EventEnvelope<CommonPayload>>
{
    public async Task Consume(ConsumeContext<EventEnvelope<CommonPayload>> context)
    {
        var incoming = context.Message;

        if (!productionFlow.IsSubscribedTo(AgentRoles.Reviewer, incoming.EventType))
        {
            return;
        }

        var specValidation = await productionSpecValidator.ValidateAsync(
            incoming,
            AgentRoles.Reviewer,
            context.CancellationToken);
        EnsureValidSpec(specValidation);

        var startedAt = DateTimeOffset.UtcNow;
        var videoArtifact = GetRequiredArtifact(incoming, "videoUri");

        logger.LogInformation(
            "{AgentRole} consumed {EventType}. ProductionId={ProductionId}, Video={VideoArtifact}",
            AgentRoles.Reviewer,
            incoming.EventType,
            incoming.ProductionId,
            videoArtifact.Uri);

        await Task.Delay(TimeSpan.FromSeconds(2), context.CancellationToken);

        var report = $"""
            # Production {incoming.ProductionId}

            ## Reviewer
            Quality review:
            Result: Passed.

            Reviewed output:
            - URI: {videoArtifact.Uri}
            - Media type: {videoArtifact.MediaType}
            - Description: {videoArtifact.Description ?? "not provided"}

            Checks:
            - Final output artifact exists.
            - Final output is published as videoUri.
            - Voiceover artifact is published when available.
            - Artifact chain can be inspected through the production console.

            Reviewer note:
            This is a dummy review. Later this step can inspect real media outputs and publish ReviewFailed with targeted revision requests.
            """;

        var artifactUri = await ArtifactText.SaveAsync(
            artifactStore,
            report,
            $"productions/{incoming.ProductionId}/05-reviewer/review-report.txt",
            context.CancellationToken);

        var artifact = new ArtifactReference(
            artifactUri,
            "text/plain",
            "Review report generated by the reviewer agent.");

        var publication = productionFlow.GetRequiredPublication<CommonPayload>(
            AgentRoles.Reviewer,
            incoming.EventType);

        var payload = CommonPayload.Create(
            publication.EventType,
            AgentRoles.Reviewer,
            attributes: new Dictionary<string, string>(incoming.Payload.Attributes)
            {
                ["reviewReportUri"] = artifact.Uri,
                ["reviewPassed"] = bool.TrueString
            },
            artifacts: [artifact],
            data: new Dictionary<string, object?>
            {
                ["findings"] = "Stub review passed. Full quality checks will be implemented later."
            });

        var outgoing = EventEnvelope<CommonPayload>.Create(
            publication.EventType,
            incoming.ProductionId,
            AgentRoles.Reviewer,
            payload,
            incoming.CorrelationId,
            incoming.EventId);

        await productionRepository.RecordArtifactAsync(
            incoming.ProductionId,
            AgentRoles.Reviewer,
            artifact,
            context.CancellationToken);

        await productionRepository.RecordAgentRunAsync(
            new AgentRunRecord(
                Guid.NewGuid(),
                incoming.ProductionId,
                AgentRoles.Reviewer,
                incoming.EventId,
                outgoing.EventId,
                videoArtifact.Uri,
                artifact.Uri,
                "Completed",
                startedAt,
                DateTimeOffset.UtcNow,
                "Created a final review report for the published output artifact."),
            context.CancellationToken);

        await productionRepository.RecordEventAsync(outgoing, context.CancellationToken);
        await productionRepository.UpdateProductionStatusAsync(
            incoming.ProductionId,
            ProductionStatus.ReviewPassed.ToString(),
            context.CancellationToken);

        await eventPublisher.PublishAsync(outgoing, context.CancellationToken);
    }

    private static ArtifactReference GetRequiredArtifact(
        EventEnvelope<CommonPayload> incoming,
        string outputKey)
    {
        if (incoming.Payload.Attributes.TryGetValue(outputKey, out var uri) &&
            !string.IsNullOrWhiteSpace(uri))
        {
            return incoming.Payload.Artifacts.FirstOrDefault(artifact => artifact.Uri == uri) ??
                new ArtifactReference(uri, "application/octet-stream");
        }

        return incoming.Payload.Artifacts.First();
    }

    private static void EnsureValidSpec(ProductionSpecValidationResult validation)
    {
        if (!validation.IsValid)
        {
            throw new InvalidOperationException(
                $"Production spec preflight failed for {validation.Stage.AgentRole}: {string.Join("; ", validation.Errors)}");
        }
    }
}
